name: RDF Syntax Check

on:
  push:
    branches: ["main"]
    paths:
      - '**.ttl'
      - '**.trig'
      - '**.nt'
      - '**.nq'
      - '**.rdf'
      - '**.trix'
      - '**.jsonld'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rdf-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.4
